name: build cron

on:
  schedule:
    - cron: '30 3 * * 1,4'

jobs:
  check_update:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/check_update.yml
    secrets:
      CACHE_NAME: ${{ secrets.CACHE_NAME }}

  vpn_test:
    needs: check_update
    if: needs.check_update.outputs.should_test == 'true'
    uses: ./.github/workflows/vpn_test.yml

  buildx:
    needs: [check_update, vpn_test]
    if: needs.check_update.outputs.should_update == 'true'
    uses: ./.github/workflows/buildx.yml
    secrets:
      CACHE_NAME: ${{ secrets.CACHE_NAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      BUILD_ONLY: ${{ secrets.BUILD_ONLY }}